version: "3.8"

services:

  php:
    image: php:8.4-fpm-alpine
    container_name: symfony
    working_dir: /var/www/symfony
    network_mode: host
    volumes:
      - /sandbox/workspace/demo-comparaison/demo-symfony:/var/www/symfony
    restart: unless-stopped
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: demo_symfony_nginx
    network_mode: host
    depends_on:
      - php
    ports:
      - "8903:80"
    volumes:
      - /sandbox/workspace/demo-comparaison/demo-symfony:/var/www/symfony:ro
      - /sandbox/workspace/demo-symfony/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_PASSWORD=demo123456
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
    ports:
      - "3307:3306"
    volumes:
      - demo_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    network_mode: host
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8905:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  demo_data: