version: "3.8"

services:

  php:
    build:
      context: .
    container_name: symfony
    working_dir: /var/www/symfony
    environment:
      - APP_ENV=dev
      - APP_SECRET=34a1be6a7ab09cb639b66554513417e6
      - DATABASE_URL=mysql://demo:demo123456@mysql:3306/demo?serverVersion=8.0
    volumes:
      - symfony_app:/var/www/symfony
    restart: unless-stopped
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: demo_symfony_nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - symfony_app:/var/www/symfony:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_PASSWORD=demo123456
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
    ports:
      - "3307:3306"
    volumes:
      - demo_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8888:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  demo_data:
  symfony_app: